# Generated by Django 4.2.2 on 2023-06-25 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='biblioteca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=120, verbose_name='titulo')),
                ('img', models.ImageField(null=True, upload_to='imagenes/', verbose_name='img')),
                ('des', models.CharField(max_length=200, null=True, verbose_name='des')),
            ],
        ),
    ]
