# Generated by Django 4.2.2 on 2023-09-09 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=120, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=120, verbose_name='apellido')),
                ('correo', models.EmailField(max_length=120, verbose_name='correo')),
                ('telefono', models.CharField(max_length=120, verbose_name='telefono')),
            ],
        ),
        migrations.AddField(
            model_name='biblioteca',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='des',
            field=models.CharField(max_length=200, null=True, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='img',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='imagenes'),
        ),
        migrations.CreateModel(
            name='prestamos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateField(auto_now_add=True, verbose_name='fecha_prestamo')),
                ('fecha_devolucion', models.DateField(verbose_name='fecha_devolucion')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('id_libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.biblioteca')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.users')),
            ],
        ),
    ]
